apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qdl3s7vae-python
  janus-idp.io/tekton: qdl3s7vae-python
  backstage.io/kubernetes-id: qdl3s7vae-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qdl3s7vae-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
