apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qdl3s7vae-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qdl3s7vae-python 
  name: qdl3s7vae-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qdl3s7vae-python 
